### ISSUE TITLE
打开运行，输入开始期和结束期，显示了正在下载，然后报错闪退

### ISSUE THREAD

**Issue by CoolHeads** [wanglu58/fulibuscrawler#1]
打开运行，输入开始期和结束期，显示了正在下载，然后报错闪退。使用管理员身份运行依然不行，pip安装过了。

**Comment by wanglu58** [comment]
我这边刚测试了下还是正常的，按您的描述应该是网络问题，第一种办法您可以尝试把代码中的三处https://fulibus.net/改成最新的https://fuliba2021.net/再试试。第二种办法下载打包好的exe文件一键运行。[https://github.com/wanglu58/fulibuscrawler/releases](url)

**Comment by wanglu58** [comment]
我这边刚测试了下还是正常的，按您的描述应该是网络问题，第一种办法您可以尝试把代码中的三处https://fulibus.net/改成最新的https://fuliba2021.net/再试试。第二种办法下载打包好的exe文件一键运行。https://github.com/wanglu58/fulibuscrawler/releases

**Comment by wanglu58** [comment]
我这边刚测试了下还是正常的，按您的描述应该是网络问题，第一种办法您可以尝试把代码中的三处https://fulibus.net/改成最新的https://fuliba2021.net/再试试。第二种办法下载打包好的exe文件一键运行。

**Comment by wanglu58** [comment]
我这边刚测试了下还是正常的，按您的描述应该是网络问题，第一种办法您可以尝试把代码中的三处
https://fulibus.net/
改成最新的
https://fuliba2021.net/
再试试。第二种办法下载打包好的exe文件一键运行。
https://github.com/wanglu58/fulibuscrawler/releases

**Comment by wanglu58** [comment]
我这边刚测试了下还是正常的，按您的描述应该是网络问题，第一种办法您可以尝试把代码中的三处
https://fulibus.net/
改成最新的
https://fuliba2021.net/
再试试。
第二种办法下载打包好的exe文件一键运行。
https://github.com/wanglu58/fulibuscrawler/releases

**Comment by CoolHeads** [comment]
我看了一下代码 debug的时候 是 response = requests.get('https://fuliba2021.net/2021067.html') 这句话报错，提示是：ValueError: check_hostname requires server_hostname

**Comment by CoolHeads** [comment]
搞定了，是网络问题，我关了vpn就好了。网上还有个说法是pip install urllib3==1.25.8   降低版本。这个我没有尝试，我直接关掉vpn即可使用。感谢！

**Comment by CoolHeads** [comment]
有的图片能下载成功，有的下载失败，这个是什么原因呢？

**Comment by wanglu58** [comment]
下载失败说明网站图片本身就已经无法显示了！
