### ISSUE TITLE
2021年12月30日 功能不可用，下载运行报错。使用源码运行也报错。

### ISSUE THREAD

**Issue by CoolHeads** [wanglu58/fulibuscrawler#2]

**Comment by CoolHeads** [comment]
2021年12月30日 功能不可用，下载运行报错。使用源码运行也报错。

**Comment by bandianma** [comment]
2021年12月31日 功能不可用，下载运行报错。使用源码运行也报错。

**Comment by wanglu58** [comment]
我这边测试了可用。你可以切换为最新地址再试下，或者把运行日志发过来我看看。

**Comment by wanglu58** [comment]
我这边测试可用。你可以切换为福利吧最新地址再试下，或者把运行日志发过来我看看。

**Comment by wanglu58** [comment]
我这边测试可用。你可以切换为福利吧最新地址再试下，或者把运行日志发过来我看看。（记得关闭代理）

**Comment by CoolHeads** [comment]
![image](https://user-images.githubusercontent.com/25093179/148149693-12993fa5-dc4c-4f4a-9bc9-4b6f8ff69684.png)
报错内容见上图。
url已修改：https://fuliba2021.net/

**Comment by wanglu58** [comment]
包没安装，请运行以下命令安装：
```
pip3 install requests -i https://pypi.doubanio.com/simple/
pip3 install beautifulsoup4 -i https://pypi.doubanio.com/simple/
pip3 install lxml -i https://pypi.doubanio.com/simple/
```

**Comment by CoolHeads** [comment]
可以了
闹了个笑话，代码被我不小心修改了。还原就可以了。
